printWidth: 200
tabWidth: 4
semi: true
arrowParens: avoid

overrides:
  - files:
      - ".prettierrc.yml"
      - ".eslintrc.yml"
      - ".github/workflows/*.yml"
      - ".pre-commit-config.yaml"
    options:
      tabWidth: 2
