printWidth: 160
tabWidth: 4
semi: true
arrowParens: avoid
trailingComma: es5

overrides:
  - files:
      - ".prettierrc.yml"
      - ".eslintrc.yml"
      - ".github/workflows/*.yml"
      - ".pre-commit-config.yaml"
    options:
      tabWidth: 2
