repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.11.0"
    hooks:
      - id: eslint
  - repo: https://github.com/prettier/prettier
    rev: "2.1.2"
    hooks:
      - id: prettier
